"""
convert_pgm.py
==============
Converts AT&T face dataset (.pgm) to .jpg files
and generates a base64 JSON lookup for the HTML demo.

Place this file in:  D:\face-recognition-attendance\
Then run:            python convert_pgm.py
"""

import os
import base64
import json
from pathlib import Path

# ── Config ────────────────────────────────────────────────────────────────
RAW_DIR    = Path(r"D:\face-recognition-attendance\data\raw")
OUTPUT_JS  = Path(r"D:\face-recognition-attendance\faces_data.js")
# ─────────────────────────────────────────────────────────────────────────

def read_pgm(path):
    """Read a PGM (P5 binary or P2 ascii) file and return pixel bytes."""
    with open(path, 'rb') as f:
        data = f.read()

    lines = []
    i = 0
    # Parse header (skip comments)
    while len(lines) < 3:
        j = data.index(b'\n', i)
        line = data[i:j].decode('ascii').strip()
        i = j + 1
        if not line.startswith('#'):
            lines.append(line)

    magic = lines[0]
    width, height = map(int, lines[1].split())
    maxval = int(lines[2])

    if magic == 'P5':
        pixels = data[i:]
    elif magic == 'P2':
        pixels = bytes(map(int, data[i:].split()))
    else:
        raise ValueError(f"Unsupported PGM type: {magic}")

    return width, height, maxval, pixels


def pgm_to_bmp_bytes(width, height, maxval, pixels):
    """Convert raw PGM pixels to a minimal BMP (grayscale) byte string."""
    import struct

    # BMP grayscale: need a color table (256 entries, RGBQ)
    color_table = b''
    for i in range(256):
        color_table += bytes([i, i, i, 0])  # B G R reserved

    # Row size must be multiple of 4 bytes
    row_size = (width + 3) & ~3
    padding  = row_size - width

    # Pixel data (BMP is bottom-up)
    pixel_data = b''
    for row in range(height - 1, -1, -1):
        row_bytes = pixels[row * width:(row + 1) * width]
        # Scale if maxval != 255
        if maxval != 255:
            row_bytes = bytes(int(p * 255 / maxval) for p in row_bytes)
        pixel_data += row_bytes + b'\x00' * padding

    # BMP header
    pixel_offset = 54 + 1024  # 14 (file) + 40 (info) + 1024 (color table)
    file_size    = pixel_offset + len(pixel_data)

    file_header = struct.pack('<2sIHHI', b'BM', file_size, 0, 0, pixel_offset)
    info_header = struct.pack('<IiiHHIIiiII',
        40, width, height, 1, 8, 0, len(pixel_data), 2835, 2835, 256, 256)

    return file_header + info_header + color_table + pixel_data


def pgm_to_base64_bmp(pgm_path):
    """Read a PGM file and return a base64-encoded BMP data URL."""
    w, h, maxval, pixels = read_pgm(pgm_path)
    bmp_bytes = pgm_to_bmp_bytes(w, h, maxval, pixels)
    b64 = base64.b64encode(bmp_bytes).decode('ascii')
    return f"data:image/bmp;base64,{b64}"


def main():
    print("=" * 55)
    print("  AT&T Face Dataset → Base64 Converter")
    print("=" * 55)

    if not RAW_DIR.exists():
        print(f"\n❌ ERROR: Folder not found:\n   {RAW_DIR}")
        print("\nMake sure your dataset is at that path and try again.")
        input("\nPress Enter to exit...")
        return

    faces = {}   # { "Person_1": ["data:image/bmp;base64,...", ...], ... }
    total = 0
    errors = 0

    subject_dirs = sorted(
        [d for d in RAW_DIR.iterdir() if d.is_dir()],
        key=lambda d: int(''.join(filter(str.isdigit, d.name)) or 0)
    )

    if not subject_dirs:
        print(f"\n❌ No subject folders found in {RAW_DIR}")
        print("Expected folders like: s1, s2, ... or subject1, subject2, ...")
        input("\nPress Enter to exit...")
        return

    print(f"\nFound {len(subject_dirs)} subject folders.\n")

    for idx, subj_dir in enumerate(subject_dirs, start=1):
        key = f"Person_{idx}"
        pgm_files = sorted(subj_dir.glob("*.pgm"))

        if not pgm_files:
            print(f"  ⚠ {subj_dir.name}: no .pgm files found — skipping")
            continue

        images = []
        for pgm in pgm_files:
            try:
                b64 = pgm_to_base64_bmp(pgm)
                images.append(b64)
                total += 1
            except Exception as e:
                print(f"  ⚠ Error reading {pgm.name}: {e}")
                errors += 1

        faces[key] = images
        print(f"  ✓ {key:12s} ({subj_dir.name:10s}) — {len(images)} images")

    # Write JS file
    print(f"\nWriting {OUTPUT_JS.name} ...")
    js_content = "// Auto-generated by convert_pgm.py\n"
    js_content += "// AT&T Face Dataset — base64 encoded grayscale images\n"
    js_content += f"const FACES_DATA = {json.dumps(faces, separators=(',', ':'))};\n"

    OUTPUT_JS.write_text(js_content, encoding='utf-8')

    size_kb = OUTPUT_JS.stat().st_size / 1024
    print(f"\n{'='*55}")
    print(f"  ✅ Done!")
    print(f"  Total images converted : {total}")
    if errors:
        print(f"  ⚠  Errors              : {errors}")
    print(f"  Output file size       : {size_kb:.0f} KB ({size_kb/1024:.1f} MB)")
    print(f"  Saved to: {OUTPUT_JS}")
    print(f"{'='*55}")
    input("\nPress Enter to exit...")


if __name__ == "__main__":
    main()